### ISSUE TITLE
FSK-lab seems not to install R packages under Linux?

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#314]
I tried to run the full norovirus model under linux in a freshly installed KNIME 3.7.1.
The runner node fails with the following message:
 
`ERROR FSK Runner           2:3        Execute failed: R evaluation failed: "pkgDep(c('foreach', 'ggplot2', 'doParallel', 'mc2d', 'gridExtra', 'foreach', 'ggplot2', 'doParallel', 'mc2d', 'gridExtra'), type = 'source', Rversion = '3.0')"
`

I was using ICPMF update site and I know that in R all these packages were installed and running before.

**Comment by miguelalba** [comment]
This ticket is named wrongly. By plugins we understand the Eclipse plugins, that is, KNIME and FSK-Lab. The error here is FSK-Lab not downloading the R packages. This was reproduced recently.

**Comment by miguelalba** [comment]
@llavall this ticket is solved in the release candidate 3 for 1.9.0 at https://dl.bintray.com/fsk/1.9.0-rc3. Please test and mark this ticket as done if it works for you. Thanks.

**Comment by llavall** [comment]
1. Was able to run the combined test workflow in my Linux-VM

2. Was still not able to run all models in KNIME Testserver - will send the results via mail.

3. On Mac the runner of both workflows failed - don't know why. (Execute failed: Invalid result. Execution failed. Reason: Incorrect implementation; the execute method in RunnerNodeModel returned null or an incorrect number of output tables.)

4. I don't know where the .FSK is saved - did not remove it.

Looks for me like the result with the last version - did it work for you under Linux for all models?

**Comment by mfilter** [comment]
@llavall : please check if it now works

**Comment by llavall** [comment]
@mfilter my test under Linux on the KNIME server was confirmed without error already during the web meeting yesterday. Changes were adding the proxy setting to R and installing the legacy nodes

on my Mac I have no success, but that can have various reasons.
